services:
  client:
    container_name: smash-league-client
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "npm install; npm run build; npm run start;"
    environment:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - client:/usr/src/app/client
  socket:
    container_name: smash-league-socket
    build: 
      context: .
      dockerfile: socket.Dockerfile
    command: bash -c "node server.mjs"
    environment:
      - .env
    ports:
      - "3005:3005"
    restart: unless-stopped
    volumes:
      - socket:/usr/src/app/socket

volumes:
  client: 
  socket: 